"""Markdown report of the source-side lineage: every physical source down
to its tables (and, when known, the remote view/entity) and columns.

Canonical, reusable place for this report - uses `render_source_tree_lines`
(navigation.py) for the ASCII tree, so the CLI/notebook `print_source_schema()`
and this report can never drift apart."""

from __future__ import annotations

from pathlib import Path

import networkx as nx

from .navigation import render_source_tree_lines, source_schema


def render_source_tree_markdown(graph: nx.DiGraph, title: str = "Source Lineage Report") -> str:
    """Overview ASCII tree, then one section per source with a summary
    table (columns, reliability, renames)."""
    schema = source_schema(graph)

    lines: list[str] = [f"# {title}\n"]
    lines.append(
        "Generated by `pbix_atlas.reports.render_source_tree_markdown(graph)`. "
        "A source's full URL (including query string) is its identity - two "
        "calls to the same endpoint with different parameters are different "
        "sources. A `view` is the remote entity/table name, when different "
        "from the local query name (e.g. OData).\n"
    )
    lines.append(
        "**Column reliability** - `⚠️ unresolved rename` means the names shown "
        "were captured *after* a rename that couldn't be resolved statically "
        "(e.g. driven by a lookup table): they are not guaranteed to be the "
        "source's original names. `renamed` means a column's name differs from "
        "its original source name via a rename that *was* resolved statically - "
        "both names are shown.\n"
    )

    lines.append("## Overview\n")
    lines.append("```")
    lines.extend(render_source_tree_lines(graph))
    lines.append("```\n")

    for source, tables in schema.items():
        n_cols = sum(len(t["columns"]) for t in tables.values())
        n_unreliable = sum(1 for t in tables.values() if not t["names_reliable"])
        lines.append(f"## Source: `{source}`\n")
        summary = f"{len(tables)} table(s), {n_cols} column(s) total"
        if n_unreliable:
            summary += f", {n_unreliable} table(s) with unresolved renames"
        lines.append(summary + ".\n")

        lines.append("| Table | View | Columns | Reliability | Preview |")
        lines.append("|---|---|---|---|---|")
        for table, info in tables.items():
            cols = info["columns"]
            view = f"`{info['view']}`" if info["view"] else "_(same as table)_"
            reliability = "✅ ok" if info["names_reliable"] else "⚠️ unresolved rename"
            preview = ", ".join(cols[:6]) + (", ..." if len(cols) > 6 else "") if cols else "_(none extracted)_"
            lines.append(f"| `{table}` | {view} | {len(cols)} | {reliability} | {preview} |")
        lines.append("")

        renamed_tables = {t: i["renamed_columns"] for t, i in tables.items() if i.get("renamed_columns")}
        if renamed_tables:
            lines.append("**Renamed columns** (current name ← original source name):\n")
            for table, mapping in renamed_tables.items():
                pairs = ", ".join(f"`{new}` ← `{old}`" for new, old in mapping.items())
                lines.append(f"- `{table}`: {pairs}")
            lines.append("")

    return "\n".join(lines)


def write_source_tree_report(graph: nx.DiGraph, path: str | Path, title: str = "Source Lineage Report") -> Path:
    """Renders `render_source_tree_markdown` and writes it to `path`."""
    path = Path(path)
    path.write_text(render_source_tree_markdown(graph, title=title), encoding="utf-8")
    return path
